import { createHash, randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { lstat, mkdir, open, rename, rm } from "node:fs/promises";
import path from "node:path";
import { zipSync } from "fflate";
import { ArtifactRefSchema, AuthorOutputSchema, type ArtifactFileRef, type ArtifactRef } from "../../shared/contracts.js";
import type { ArtifactFileContent, ArtifactStore, PublishedResult, WriteVersionRequest } from "../../shared/ports.js";

const names = ["solution.ts", "solution.test.ts"] as const;
const safeId = /^[A-Za-z0-9_-]{1,100}$/;
const maxArtifactBytes = 64 * 1024;

function sha256(data: string | Uint8Array): string { return createHash("sha256").update(data).digest("hex"); }
function id(value: string): string {
  if (!safeId.test(value)) throw new Error("Unsafe task or version ID");
  return value;
}
function testSource(functionName: string, cases: WriteVersionRequest["candidate"]["cases"]): string {
  return `// Generated by the trusted test harness.\nexport const functionName = ${JSON.stringify(functionName)};\nexport const cases = ${JSON.stringify(cases, null, 2)} as const;\n\nimport test from "node:test";\nimport assert from "node:assert/strict";\nimport * as solution from "./solution.ts";\n\nfor (const testCase of cases) {\n  test(testCase.name, () => {\n    const args = structuredClone(testCase.args);\n    const before = structuredClone(args);\n    const fn: unknown = Reflect.get(solution, functionName);\n    if (typeof fn !== "function") throw new TypeError("Exported function missing");\n    const actual = fn(...args);\n    assert.deepStrictEqual(args, before, "function mutated its input");\n    assert.deepStrictEqual(actual, testCase.expected);\n  });\n}\n`;
}
async function requireDirectory(directory: string): Promise<void> {
  const stat = await lstat(directory);
  if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error(`Unsafe directory: ${directory}`);
}
async function readRegular(file: string): Promise<Uint8Array> {
  const handle = await open(file, constants.O_RDONLY | constants.O_NOFOLLOW);
  try {
    if (!(await handle.stat()).isFile()) throw new Error("Unsafe non-file artifact");
    return await handle.readFile();
  } finally { await handle.close(); }
}
async function writeNew(file: string, bytes: string | Uint8Array): Promise<void> {
  const handle = await open(file, constants.O_WRONLY | constants.O_CREAT | constants.O_EXCL | constants.O_NOFOLLOW, 0o600);
  try { await handle.writeFile(bytes); await handle.sync(); } finally { await handle.close(); }
}
async function ensureDir(directory: string): Promise<void> {
  await mkdir(directory, { recursive: true, mode: 0o700 });
  await requireDirectory(directory);
}
function manifestBody(ref: Omit<ArtifactRef, "manifestHash">): object {
  return { taskId: ref.taskId, versionId: ref.versionId, files: ref.files.map((file) => ({
    artifactId: file.artifactId, path: file.path, sha256: file.sha256, bytes: file.bytes,
  })) };
}
function manifestHash(ref: Omit<ArtifactRef, "manifestHash">): string {
  return sha256(JSON.stringify(manifestBody(ref)));
}
function sameRef(a: ArtifactRef, b: ArtifactRef): boolean {
  return a.manifestHash === b.manifestHash && JSON.stringify(manifestBody(a)) === JSON.stringify(manifestBody(b));
}

export class LocalArtifactStore implements ArtifactStore {
  constructor(private readonly dataRoot: string) {}

  private taskRoot(taskId: string): string { return path.join(this.dataRoot, "tasks", id(taskId)); }
  private versionDir(taskId: string, versionId: string): string { return path.join(this.taskRoot(taskId), "revisions", id(versionId)); }
  private async ensureTask(taskId: string): Promise<void> {
    await ensureDir(this.dataRoot);
    await ensureDir(path.join(this.dataRoot, "tasks"));
    await ensureDir(this.taskRoot(taskId));
  }
  private async assertTask(taskId: string): Promise<void> {
    await requireDirectory(this.dataRoot);
    await requireDirectory(path.join(this.dataRoot, "tasks"));
    await requireDirectory(this.taskRoot(taskId));
  }
  private async readManifest(directory: string): Promise<ArtifactRef> {
    await requireDirectory(directory);
    const ref = ArtifactRefSchema.parse(JSON.parse(Buffer.from(await readRegular(path.join(directory, "manifest.json"))).toString("utf8")));
    if (manifestHash(ref) !== ref.manifestHash) throw new Error("Manifest hash mismatch");
    if (ref.files[0]?.path !== names[0] || ref.files[1]?.path !== names[1]) throw new Error("Invalid manifest file set");
    for (const file of ref.files) {
      if (file.artifactId !== `${ref.versionId}:${file.path}`) throw new Error("Invalid artifact ID");
      const bytes = await readRegular(path.join(directory, file.path));
      if (bytes.byteLength !== file.bytes || sha256(bytes) !== file.sha256) throw new Error("Artifact hash mismatch");
    }
    return ref;
  }
  async writeVersion(request: WriteVersionRequest): Promise<ArtifactRef> {
    const taskId = id(request.taskId);
    const candidate = AuthorOutputSchema.parse(request.candidate);
    if (candidate.cases.length > 100) throw new Error("Test case count limit exceeded");
    const versionId = randomUUID();
    const content = [candidate.solutionTs, testSource(candidate.functionName, candidate.cases)];
    const totalBytes = content.reduce((sum, value) => sum + Buffer.byteLength(value), 0);
    if (totalBytes > maxArtifactBytes) throw new Error("Artifact size limit exceeded");
    await this.ensureTask(taskId);
    const revisions = path.join(this.taskRoot(taskId), "revisions");
    await ensureDir(revisions);
    const temp = path.join(revisions, `.tmp-${randomUUID()}`);
    await mkdir(temp, { mode: 0o700 });
    try {
      const files: ArtifactFileRef[] = [];
      for (let index = 0; index < names.length; index++) {
        const bytes = Buffer.from(content[index]!);
        await writeNew(path.join(temp, names[index]), bytes);
        files.push({ artifactId: `${versionId}:${names[index]}`, path: names[index], bytes: bytes.byteLength, sha256: sha256(bytes) });
      }
      const body = { taskId, versionId, files };
      const ref: ArtifactRef = { ...body, manifestHash: manifestHash(body) };
      await writeNew(path.join(temp, "manifest.json"), JSON.stringify(ref));
      await rename(temp, this.versionDir(taskId, versionId));
      return ref;
    } catch (error) {
      await rm(temp, { recursive: true, force: true });
      throw error;
    }
  }
  async verifyVersion(input: ArtifactRef): Promise<void> {
    const ref = ArtifactRefSchema.parse(input);
    await this.assertTask(ref.taskId);
    await requireDirectory(path.join(this.taskRoot(ref.taskId), "revisions"));
    const disk = await this.readManifest(this.versionDir(ref.taskId, ref.versionId));
    if (!sameRef(disk, ref)) throw new Error("Artifact reference mismatch");
  }
  async prepareWorkingCopy(ref: ArtifactRef): Promise<string> {
    await this.verifyVersion(ref);
    const work = path.join(this.taskRoot(ref.taskId), "work");
    await ensureDir(work);
    const target = path.join(work, id(ref.versionId));
    try {
      const existing = await this.readManifest(target);
      if (!sameRef(existing, ref)) throw new Error("Working copy conflict");
      return target;
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    await this.copyVersion(ref, target);
    return target;
  }
  private async copyVersion(ref: ArtifactRef, target: string): Promise<void> {
    const temp = path.join(path.dirname(target), `.tmp-${randomUUID()}`);
    await mkdir(temp, { mode: 0o700 });
    try {
      const source = this.versionDir(ref.taskId, ref.versionId);
      for (const name of [...names, "manifest.json"] as const) await writeNew(path.join(temp, name), await readRegular(path.join(source, name)));
      await this.readManifest(temp);
      await rename(temp, target);
    } catch (error) {
      await rm(temp, { recursive: true, force: true });
      throw error;
    }
  }
  async publishApprovedVersion(ref: ArtifactRef, approval: { decision: "approve" | "reject"; versionId: string; manifestHash: string }): Promise<PublishedResult> {
    if (approval.decision !== "approve" || approval.versionId !== ref.versionId || approval.manifestHash !== ref.manifestHash) throw new Error("Stale or rejected approval");
    await this.verifyVersion(ref);
    const target = path.join(this.taskRoot(ref.taskId), "result");
    try {
      const existing = await this.readManifest(target);
      if (!sameRef(existing, ref)) throw new Error("Published result conflict");
      return { taskId: ref.taskId, versionId: ref.versionId, manifestHash: ref.manifestHash, resultPath: target, files: ref.files };
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    await this.copyVersion(ref, target);
    return { taskId: ref.taskId, versionId: ref.versionId, manifestHash: ref.manifestHash, resultPath: target, files: ref.files };
  }
  async getFile(taskId: string, artifactId: string, source: "revision" | "result"): Promise<ArtifactFileContent> {
    id(taskId);
    const [versionId, name, extra] = artifactId.split(":");
    if (extra !== undefined || !versionId || !names.includes(name as typeof names[number])) throw new Error("Invalid artifact ID");
    id(versionId);
    await this.assertTask(taskId);
    if (source === "revision") await requireDirectory(path.join(this.taskRoot(taskId), "revisions"));
    const directory = source === "result" ? path.join(this.taskRoot(taskId), "result") : this.versionDir(taskId, versionId);
    const ref = await this.readManifest(directory);
    if (ref.taskId !== taskId || ref.versionId !== versionId) throw new Error("Artifact belongs to another task or version");
    const metadata = ref.files.find((file) => file.artifactId === artifactId);
    if (!metadata) throw new Error("Artifact not found");
    return { metadata, content: Buffer.from(await readRegular(path.join(directory, metadata.path))).toString("utf8") };
  }
  async getResultZip(taskId: string, ref: ArtifactRef): Promise<Uint8Array> {
    if (taskId !== ref.taskId) throw new Error("Task mismatch");
    await this.assertTask(taskId);
    const result = path.join(this.taskRoot(id(taskId)), "result");
    const disk = await this.readManifest(result);
    if (!sameRef(disk, ref)) throw new Error("Published result conflict");
    return zipSync(Object.fromEntries(await Promise.all(ref.files.map(async (file) => [file.path, await readRegular(path.join(result, file.path))]))));
  }
}
