import { z } from "zod";
import type { WriteVersionRequest } from "../tasks/ports.js";
import { TestCaseSchema } from "../tasks/types.js";

const TestArtifactSchema = z.object({
  functionName: z.string().regex(/^[A-Za-z_$][\w$]*$/),
  cases: z.array(TestCaseSchema).min(1).max(100),
});
export type TestArtifactData = z.infer<typeof TestArtifactSchema>;

// Создаёт запускаемый файл тестов и метаданные для безопасного чтения без исполнения TypeScript.
export function renderTestArtifact(
  functionName: string,
  cases: WriteVersionRequest["candidate"]["cases"],
): string {
  const metadata = Buffer.from(JSON.stringify({ functionName, cases })).toString("base64");
  return `// Test cases: ${metadata}
// Generated by the trusted test harness.
export const functionName = ${JSON.stringify(functionName)};
export const cases = ${JSON.stringify(cases, null, 2)} as const;

import test from "node:test";
import assert from "node:assert/strict";
import * as solution from "./solution.ts";

for (const testCase of cases) {
  // Сравнивает результат функции с ожидаемым и проверяет неизменность входных данных.
  test(testCase.name, () => {
    const args = structuredClone(testCase.args);
    const before = structuredClone(args);
    const fn: unknown = Reflect.get(solution, functionName);
    if (typeof fn !== "function") throw new TypeError("Exported function missing");

    const actual = fn(...args);

    assert.deepStrictEqual(args, before, "function mutated its input");
    assert.deepStrictEqual(actual, testCase.expected);
  });
}
`;
}

// Читает данные тестов и сверяет весь файл с генератором, исключая подмену экспортов или тела.
export function parseTestArtifact(source: string): TestArtifactData {
  const prefix = "// Test cases: ";
  const firstLine = source.slice(0, source.indexOf("\n"));
  if (!firstLine.startsWith(prefix)) throw new Error("Invalid trusted test artifact");
  const encoded = firstLine.slice(prefix.length);
  const value: unknown = JSON.parse(Buffer.from(encoded, "base64").toString("utf8"));
  const data = TestArtifactSchema.parse(value);
  if (source !== renderTestArtifact(data.functionName, data.cases))
    throw new Error("Invalid trusted test artifact");
  return data;
}
