import { Worker } from "node:worker_threads";
import { TestCaseSchema, type ArtifactRef, type CheckResult } from "../../shared/contracts.js";
import type { ArtifactStore, CheckRunner, CheckRunHooks } from "../../shared/ports.js";

const maxTimeoutMs = 5000;
const maxMemoryBytes = 64 * 1024 * 1024;
const maxCases = 100;

function parseGeneratedTests(source: string): { functionName: string; cases: Array<{ name: string; args: unknown[]; expected: unknown }> } {
  const match = /^\/\/ Generated by the trusted test harness\.\nexport const functionName = ("(?:[^"\\]|\\.)*");\nexport const cases = ([\s\S]+?) as const;\n\nimport test from "node:test";/.exec(source);
  if (!match) throw new Error("Invalid trusted test artifact");
  const functionName = JSON.parse(match[1]!) as unknown;
  const raw = JSON.parse(match[2]!) as unknown;
  if (typeof functionName !== "string" || !/^[A-Za-z_$][\w$]*$/.test(functionName)) throw new Error("Invalid function name");
  if (!Array.isArray(raw) || raw.length < 1 || raw.length > maxCases) throw new Error("Invalid test count");
  const cases = raw.map((item) => TestCaseSchema.parse(item));
  return { functionName, cases };
}

interface WorkerResult {
  compilation: CheckResult["compilation"];
  tests: CheckResult["tests"];
  passedCases: number;
  failedCases: number;
  fatal?: string;
}

export class QuickJsCheckRunner implements CheckRunner {
  constructor(private readonly store: ArtifactStore) {}

  async run(ref: ArtifactRef, hooks: CheckRunHooks): Promise<CheckResult> {
    if (!Number.isInteger(hooks.timeoutMs) || hooks.timeoutMs < 1 || hooks.timeoutMs > maxTimeoutMs) throw new Error("Invalid check timeout");
    if (!Number.isInteger(hooks.memoryLimitBytes) || hooks.memoryLimitBytes < 1024 * 1024 || hooks.memoryLimitBytes > maxMemoryBytes) throw new Error("Invalid check memory limit");
    if (hooks.signal.aborted) throw new Error("Check aborted");
    await this.store.verifyVersion(ref);
    const solutionRef = ref.files.find((file) => file.path === "solution.ts");
    const testRef = ref.files.find((file) => file.path === "solution.test.ts");
    if (!solutionRef || !testRef) throw new Error("Incomplete artifact");
    const solution = await this.store.getFile(ref.taskId, solutionRef.artifactId, "revision");
    const test = await this.store.getFile(ref.taskId, testRef.artifactId, "revision");
    const { functionName, cases } = parseGeneratedTests(test.content);
    const started = Date.now();
    const worker = new Worker(new URL("./quickjs-worker.ts", import.meta.url), {
      workerData: { solutionTs: solution.content, functionName, cases, deadline: started + hooks.timeoutMs, memoryLimitBytes: hooks.memoryLimitBytes },
      resourceLimits: { maxOldGenerationSizeMb: 128, maxYoungGenerationSizeMb: 16 },
    });
    const result = await new Promise<WorkerResult>((resolve, reject) => {
      let settled = false;
      const finish = (value?: WorkerResult, error?: Error) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        hooks.signal.removeEventListener("abort", abort);
        void worker.terminate();
        if (error) reject(error); else resolve(value!);
      };
      const abort = () => finish(undefined, new Error("Check aborted"));
      const timer = setTimeout(() => finish({ compilation: { status: "timeout", details: ["Check deadline exceeded"] }, tests: { status: "timeout", details: ["Check deadline exceeded"] }, passedCases: 0, failedCases: cases.length }), hooks.timeoutMs);
      hooks.signal.addEventListener("abort", abort, { once: true });
      worker.once("message", (message: WorkerResult) => finish(message));
      worker.once("error", (error) => finish({ compilation: { status: "error", details: [String(error)] }, tests: { status: "error", details: ["Worker failed"] }, passedCases: 0, failedCases: cases.length }));
      worker.once("exit", (code) => { if (code !== 0) finish({ compilation: { status: "error", details: [`Worker exited ${code}`] }, tests: { status: "error", details: ["Worker exited"] }, passedCases: 0, failedCases: cases.length }); });
    });
    if (result.fatal) return { versionId: ref.versionId, manifestHash: ref.manifestHash, compilation: { status: "error", details: [result.fatal] }, tests: { status: "error", details: ["Check failed"] }, passedCases: 0, failedCases: cases.length, durationMs: Date.now() - started, at: new Date().toISOString() };
    return { versionId: ref.versionId, manifestHash: ref.manifestHash, compilation: result.compilation, tests: result.tests, passedCases: result.passedCases, failedCases: result.failedCases, durationMs: Date.now() - started, at: new Date().toISOString() };
  }
}
